attack_overrides:
  backdoor:
    learned:
      epochs: 10
      label_mode: corrupted
      lambda_mask: 0.001
      lambda_tv: 0.01
      learning_rate: 0.01
      patch_size_ratio: 0.15
      poison_fraction: 0.1
      target_class: 4
dataset:
  name: cifar10
  type: builtin
model:
  input_shape:
  - 3
  - 32
  - 32
  name: cnn
  num_classes: 10
  params:
    conv_filters: 32
    hidden_size: 128
  type: builtin
name: cloud_api_profile
threat_model:
  attack_goal: untargeted
  data_sensitivity: high
  deployment_scenario: cloud
  interface_exposed: api
  model_access: gray-box
  model_type: transformer
  threat_categories:
  - model_stealing
  - membership_inference
  - backdoor_attacks
  - data_poisoning
  - model_inversion
  training_data_source: mixed
