attack_overrides:
  evasion_attacks:
    cw:
      binary_search_steps: 3
      confidence: 0.1
      initial_const: 0.001
      learning_rate: 0.01
      max_iterations: 300
dataset:
  name: cifar10
  type: builtin
model:
  input_shape:
  - 3
  - 32
  - 32
  name: cnn
  num_classes: 10
  params:
    conv_filters: 32
    hidden_size: 128
  type: builtin
name: test
threat_model:
  attack_goal: targeted
  data_sensitivity: high
  deployment_scenario: cloud
  interface_exposed: api
  model_access: white-box
  model_type: cnn
  threat_categories:
  - data_poisoning
  - backdoor_attacks
  - evasion_attacks
  - model_stealing
  - membership_inference
  - model_inversion
  training_data_source: internal_clean
